# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/project_4/project_4.srcs/sources_1/bd/arm_processor/ip/arm_processor_microblaze_0_0_1/arm_processor_microblaze_0_0.xci
# IP: The module: 'arm_processor_microblaze_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/project_4/project_4.gen/sources_1/bd/arm_processor/ip/arm_processor_microblaze_0_0_1/arm_processor_microblaze_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'arm_processor_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/project_4/project_4.gen/sources_1/bd/arm_processor/ip/arm_processor_microblaze_0_0_1/arm_processor_microblaze_0_0_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'arm_processor_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/project_4/project_4.gen/sources_1/bd/arm_processor/ip/arm_processor_microblaze_0_0_1/arm_processor_microblaze_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'arm_processor_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/project_4/project_4.srcs/sources_1/bd/arm_processor/ip/arm_processor_microblaze_0_0_1/arm_processor_microblaze_0_0.xci
# IP: The module: 'arm_processor_microblaze_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/project_4/project_4.gen/sources_1/bd/arm_processor/ip/arm_processor_microblaze_0_0_1/arm_processor_microblaze_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'arm_processor_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/project_4/project_4.gen/sources_1/bd/arm_processor/ip/arm_processor_microblaze_0_0_1/arm_processor_microblaze_0_0_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'arm_processor_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/project_4/project_4.gen/sources_1/bd/arm_processor/ip/arm_processor_microblaze_0_0_1/arm_processor_microblaze_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'arm_processor_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
